services:
  db:
    image: postgres
    container_name: olympic_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=olympic_db